# Generated by Django 3.2.12 on 2022-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begginer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
